name: Build and Deploy GitHub client

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
          fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore src/Clients/PullRequestQuantifier.GitHub.Client/PullRequestQuantifier.GitHub.Client.csproj
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - name: Build
      run: dotnet build src/Clients/PullRequestQuantifier.GitHub.Client/PullRequestQuantifier.GitHub.Client.csproj --configuration Release --no-restore
    - name: dotnet publish
      run: dotnet publish src/Clients/PullRequestQuantifier.GitHub.Client/PullRequestQuantifier.GitHub.Client.csproj -c Release -o "${{env.DOTNET_ROOT}}/pullrequestquantifiergithubclient"
    - name: Deploy to Azure Web App
      if: github.ref == 'refs/heads/main'
      uses: azure/webapps-deploy@5cfb776471c748b351e1ebf5770e208a54ace016 # v2.2.19
      with:
        app-name: 'pullrequestquantifier'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_Password }}
        package: ${{env.DOTNET_ROOT}}/pullrequestquantifiergithubclient
